-- V1: create parcels table
CREATE TABLE IF NOT EXISTS parcels (

    id BIGSERIAL PRIMARY KEY,
    recipient_name VARCHAR(255) NOT NULL,
    apartment VARCHAR(50) NOT NULL,
    description TEXT,
    status VARCHAR(50) NOT NULL,
    notified BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);